
---
- hosts: k8s
  become: true
  tasks:
  - name: starting k8s cluster
    command: minikube start --driver=none


  - name: creating app-deployment
    command: kubectl apply -f /home/ubuntu/app_deployment.yml

