---
- hosts: k8s
  become: true
  tasks:

  - name: deleting previous myapp-deployment
    command: sudo kubectl delete deployments webapp-deployment


  - name: creating myapp-deployment
    command: sudo kubectl apply -f /home/ubuntu/app_deployment.yml 

      

