
---
- hosts: k8s
  become: true
  tasks:
  - name: creating nginx-deployment
    command: kubectl apply -f /home/ubuntu/nginx_deployment.yml
  - name: creating nginx-service
    command: kubectl apply -f /home/ubuntu/nginx_service.yml

